apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7and
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ahmv-tenant/rhtap-demo-app/hacbs-test-project-7and@sha256:804af532a7c9ca6bf2b35952e4f099842abf9eb0602536da669be673701b5cfc
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
